import { useSession, useSupabaseClient, useUser } from '@supabase/auth-helpers-react'
import Head from 'next/head'
import Image from 'next/image'
import { Crimson_Text, Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import { createServerSupabaseClient } from '@supabase/auth-helpers-nextjs'


const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>DevOverflow</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='w-full p-4 flex-row flex flex-b'>
        <h1 className='text-3xl bold'>DevOverflow</h1>
        <button>Sign Out</button>
      </div>
    </>
  )
}

export const getServerSideProps = async (ctx) => {
  const supabase = createServerSupabaseClient(ctx)
  const {
    data: { session },
  } = await supabase.auth.getSession()

  if(!session) {
    return {
      redirect: {
        destination: '/login',
        permanent: false,
      },
    }
  }

  return {
    props: {
      initialSession: session,
    }
  }
}